spring:
  profiles:
    active: dev
  freemarker.request-context-attribute: request
  servlet:
    multipart:
    #最大上传文件大小
      max-file-size: 20Mb
mybatis-plus:

#mapper.xml所在位置,classpath对应:resources下
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#下划线转字母大写
  global-config:
      db-column-underline: true
#实体类所做包
  typeAliasesPackage: com.infotop.entity
